Meteor.startup(function() {
    const initialJobs = [{
        "title": "Android Developer",
        "category": "Desarrollo Móvil",
        "jobtype": "Termino Fijo",
        "company": "LOOPA SAS",
        "tags": [
            "desarrollo-movil",
            "android",
            "java"
        ],
        "country": "Colombia",
        "city": "Cali",
        "remote": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
        "url": "http://loopa.io/trabajos",
        "contact": "info@loopa.io",
        "userId": "GGoJgEmC8FrcD8aXX",
        "userName": "andres@loopa.io",
        "status": "active",
        "companyImageUrl": "https://ucarecdn.com/04c10de9-9f03-4a80-b57d-827dd7beadff/",
        "htmlDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    }, {
        "title": "Web Developer",
        "category": "Desarrollo Web",
        "jobtype": "Termino Indefinido",
        "company": "UBER",
        "tags": [
            "desarrollo-web",
            "ruby-on-rails",
            "sql"
        ],
        "country": "Colombia",
        "city": "Cali",
        "remote": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
        "url": "http://uber.com.co",
        "contact": "info@uber.com",
        "userId": "GGoJgEmC8FrcD8aXX",
        "userName": "andres@loopa.io",
        "status": "active",
        "companyImageUrl": "https://cdn3.vox-cdn.com/thumbor/jBlJea_ktX_sENPJGBsN2UrK47Q=/0x34:800x567/1280x854/cdn0.vox-cdn.com/uploads/chorus_image/image/48711819/IMG_0713.0.0.jpg",
        "htmlDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    }, {
        "title": "DB Analyst",
        "category": "Desarrollo Web",
        "jobtype": "Termino Fijo",
        "company": "GOOGLE",
        "tags": [
            "sql",
            "mysql",
            "linux"
        ],
        "country": "Colombia",
        "city": "Bogotá",
        "remote": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
        "url": "http://loopa.io/trabajos",
        "contact": "info@google.com",
        "userId": "GGoJgEmC8FrcD8aXX",
        "userName": "andres@loopa.io",
        "status": "active",
        "companyImageUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/1024px-Google_%22G%22_Logo.svg.png",
        "htmlDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    }, {
        "title": "Community Manager",
        "category": "Marketing",
        "jobtype": "Termino Fijo",
        "company": "LOOPA SAS",
        "tags": [],
        "country": "Colombia",
        "city": "Bogotá",
        "remote": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
        "url": "http://loopa.io/trabajos",
        "contact": "info@loopa.io",
        "userId": "GGoJgEmC8FrcD8aXX",
        "userName": "andres@loopa.io",
        "status": "active",
        "companyImageUrl": "https://ucarecdn.com/04c10de9-9f03-4a80-b57d-827dd7beadff/",
        "htmlDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    }, {
        "title": "Web Designer",
        "category": "Diseño",
        "jobtype": "Prestación de Servicios",
        "company": "FACEBOOK",
        "tags": [
            "html",
            "css",
            "bootstrap"
        ],
        "country": "Colombia",
        "city": "Medellín",
        "remote": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
        "url": "http://loopa.io/trabajos",
        "contact": "info@facebook.io",
        "userId": "GGoJgEmC8FrcD8aXX",
        "userName": "andres@loopa.com",
        "status": "active",
        "companyImageUrl": "http://www.freelargeimages.com/wp-content/uploads/2015/05/Facebook_Vector_Logo_Hd_02.png",
        "htmlDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    }, {
        "title": "Fullstack Developer",
        "category": "Desarrollo Móvil",
        "jobtype": "Termino Indefinido",
        "company": "LOOPA SAS",
        "tags": [
            "ruby-on-rails",
            "angular",
            "mysql",
            "git"
        ],
        "country": "Colombia",
        "city": "Cali",
        "remote": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
        "url": "http://loopa.io/trabajos",
        "contact": "info@loopa.io",
        "userId": "GGoJgEmC8FrcD8aXX",
        "userName": "andres@loopa.io",
        "status": "active",
        "companyImageUrl": "https://ucarecdn.com/04c10de9-9f03-4a80-b57d-827dd7beadff/",
        "htmlDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    }, {
        "title": "Graphic Designer",
        "category": "Diseño",
        "jobtype": "Termino Fijo",
        "company": "LOOPA SAS",
        "tags": [
            "css",
            "photoshop"
        ],
        "country": "Colombia",
        "city": "Barranquilla",
        "remote": true,
        "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
        "url": "http://loopa.io/trabajos",
        "contact": "info@loopa.io",
        "userId": "GGoJgEmC8FrcD8aXX",
        "userName": "andres@loopa.io",
        "status": "active",
        "companyImageUrl": "https://ucarecdn.com/04c10de9-9f03-4a80-b57d-827dd7beadff/",
        "htmlDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur",
    }];

    if (Jobs.find().count() === 0) {

        initialJobs.forEach((job, i) => {
            Jobs.insert(job);
        });
    }
});
